- apt: pkg={{ item }} state=present
  with_items:
    - transmission-daemon
    - transmission

- apt: pkg=transmission state=present

- service: name=transmission-daemon enabled=yes

- template: src=settings.json dest=/etc/transmission-daemon/settings.json owner=debian-transmission group=debian-transmission
  notify:
    - reload transmission-daemon
    - restart transmission-daemon
