---
- hosts: all
  user: $user
  sudo: yes
  vars_files:
    - ../vars/main.yaml
  tasks:
    # install the package "curl"
    - apt: pkg=curl state=present

    # install the package "dnsutils"
    - apt: pkg=dnsutils state=present

    # dyndns with digital ocean api
    - cron: name=dyndns minute=0 job="IP=`dig +short myip.opendns.com @resolver1.opendns.com` curl https://api.digitalocean.com/domains/43342/records/304426/edit\?client_id\={{ client_id }}\&api_key\={{ api_key }}\&data\=$IP"

