---
- hosts: all
  user: $user
  sudo: yes
  handlers:
    - include: handlers/main.yaml
  tasks:
    # install the package "nginx"
    - apt: pkg=nginx state=present

    # ensure "nginx" service is enabled
    - service: name=nginx enabled=yes

    # remove "default" virtualhost
    - file: path=/etc/nginx/sites-enabled/default state=absent

    # copy virtual host
    - copy: src=templates/transmission dest=/etc/nginx/sites-enabled/transmission owner=root group=root
      notify:
        - restart nginx

