---
- hosts: all
  user: $user
  sudo: yes
  handlers:
    - include: handlers/main.yaml
  tasks:
    # install the package "minidlna"
    - apt: pkg=minidlna state=present

    # ensure "transmission-daemon" service is enabled
    - service: name=minidlna enabled=yes

    # config
    - lineinfile: dest=/etc/minidlna.conf regexp="media_dir=" line="media_dir=/media/usb0/downloads"
      notify:
        - reload minidlna
